# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d0e31b618cfe25100dd0d1c1b70b1f3b02aa050ab0967944a7924eb3e2e771860900a4f0dc598b35897e6bb1c63de2423e4b36f8303b624dca285c317468a4d3

test:
  secret_key_base: 7b7ebbae37802bfbbff857ee32f5eb07c7dadd984f8f7e83503af0c384d7a105c059dec35675f6a8b86838b0b2b569e9d0bd4a81fb8a5affc9275928d95638e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
